version: '3.3'

services:

  vantaa-pwa:
    image: vantaa-pwa
    ports:
      - 8000:8000
    command: bash -c 'npm install && npm start && npm run fetch-courses'
    depends_on:
      - postgres-dev-db
    environment:
      PORT: 8000
      USERNAME: postgres
      PASSWORD: password
      DATABASE: vantaa_pwa
      HOST: postgres-dev-db
      COURSE_UPDATE_INTERVAL: 3600000
      COURSE_API_URL: https://colosseum.grynos.com/ilmoapix/v1/course/search?com=3,6&cgt=176

  postgres-dev-db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vantaa_pwa

  admin:
    image: adminer
    ports:
      - 8080:8080