version: '3.3'

services:

  vantaa-pwa:
    image: vantaa-pwa
    ports:
      - 3000:3000
    command: bash -c 'while !</dev/tcp/postgres-dev-db/5432; do sleep 1; done; npm start'
    depends_on:
      - postgres-dev-db
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres-dev-db:5432/vantaa_pwa
      - PORT=3000

  postgres-dev-db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vantaa_pwa

  admin:
    image: adminer
    ports:
      - 8080:8080